### ISSUE TITLE
无法接收好友消息message.private

### ISSUE THREAD

**Issue by MooMXiZ1** [takayama-lily/oicq#127] opened 2021-01-26 09:52 UTC
v1.12.3和v1.13.1 都接收不到，群消息正常

**Comment by takayama-lily** [comment] 2021-01-26 11:35
无法再现，把log_level设置为trace，提供一下详细的日志？

**Comment by MooMXiZ1** [comment] 2021-01-27 01:11
![11](https://user-images.githubusercontent.com/41711944/105927749-944b2d80-607f-11eb-860d-67dc2821cec1.png)
![22](https://user-images.githubusercontent.com/41711944/105927770-9dd49580-607f-11eb-806e-74151fc745be.png)

**Comment by MooMXiZ1** [comment] 2021-01-27 01:14
[2021-01-27T09:01:27.905] [INFO] [BOT:QQ号] - 加载了42个好友，43个群。
[2021-01-27T09:01:27.910] [INFO] [BOT:QQ号] - 初始化完毕，开始处理消息。
[2021-01-27T09:01:27.915] [TRACE] [BOT:QQ号] - send:MessageSvc.PbGetMsg seq:6
[2021-01-27T09:01:27.996] [TRACE] [BOT:QQ号] - recv:MessageSvc.PbGetMsg seq:6
[2021-01-27T09:01:30.269] [TRACE] [BOT:QQ号] - recv:ConfigPushSvc.PushDomain seq:-655647230
[2021-01-27T09:01:30.503] [TRACE] [BOT:QQ号] - recv:ConfigPushSvc.PushReq seq:-655647232
[2021-01-27T09:01:30.521] [TRACE] [BOT:QQ号] - send:ConfigPushSvc.PushResp seq:7
[2021-01-27T09:01:57.150] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:8
[2021-01-27T09:01:57.200] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:8
[2021-01-27T09:02:27.170] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:9
[2021-01-27T09:02:27.217] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:9
[2021-01-27T09:02:57.184] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:10
[2021-01-27T09:02:57.227] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:10
[2021-01-27T09:02:57.232] [TRACE] [BOT:QQ号] - send:MessageSvc.PbGetMsg seq:11
[2021-01-27T09:02:57.299] [TRACE] [BOT:QQ号] - recv:MessageSvc.PbGetMsg seq:11
[2021-01-27T09:03:27.199] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:12
[2021-01-27T09:03:27.246] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:12
[2021-01-27T09:03:57.213] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:13
[2021-01-27T09:03:57.260] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:13
[2021-01-27T09:03:57.264] [TRACE] [BOT:QQ号] - send:MessageSvc.PbGetMsg seq:14
[2021-01-27T09:03:57.312] [TRACE] [BOT:QQ号] - recv:MessageSvc.PbGetMsg seq:14
[2021-01-27T09:04:27.228] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:15
[2021-01-27T09:04:27.290] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:15
[2021-01-27T09:04:36.356] [TRACE] [BOT:QQ号] - recv:OnlinePush.ReqPush seq:-1589594186
[2021-01-27T09:04:36.367] [TRACE] [BOT:QQ号] - send:OnlinePush.RespPush seq:16
[2021-01-27T09:04:41.057] [TRACE] [BOT:QQ号] - recv:OnlinePush.ReqPush seq:-1664091451
[2021-01-27T09:04:41.066] [TRACE] [BOT:QQ号] - send:OnlinePush.RespPush seq:17
[2021-01-27T09:04:41.157] [TRACE] [BOT:QQ号] - recv:MessageSvc.PushNotify seq:-1789504969
[2021-01-27T09:04:41.168] [TRACE] [BOT:QQ号] - send:MessageSvc.PbGetMsg seq:18
[2021-01-27T09:04:41.232] [TRACE] [BOT:QQ号] - recv:MessageSvc.PbGetMsg seq:18
[2021-01-27T09:04:41.239] [TRACE] [BOT:QQ号] - send:MessageSvc.PbDeleteMsg seq:19
[2021-01-27T09:04:41.287] [TRACE] [BOT:QQ号] - recv:MessageSvc.PbDeleteMsg seq:19
[2021-01-27T09:04:57.242] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:20
[2021-01-27T09:04:57.288] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:20
[2021-01-27T09:05:20.920] [TRACE] [BOT:QQ号] - recv:OnlinePush.PbPushGroupMsg seq:-1591073511
[2021-01-27T09:05:20.933] [TRACE] [BOT:QQ号] - send:OidbSvc.0x88d_0 seq:21
[2021-01-27T09:05:20.944] [TRACE] [BOT:QQ号] - send:friendlist.GetTroopMemberListReq seq:22
[2021-01-27T09:05:20.955] [TRACE] [BOT:QQ号] - send:group_member_card.get_group_member_card_info seq:23
[2021-01-27T09:05:20.987] [TRACE] [BOT:QQ号] - recv:OidbSvc.0x88d_0 seq:21
[2021-01-27T09:05:21.096] [TRACE] [BOT:QQ号] - recv:friendlist.GetTroopMemberListReq seq:22
[2021-01-27T09:05:21.334] [TRACE] [BOT:QQ号] - recv:group_member_card.get_group_member_card_info seq:23
[2021-01-27T09:05:21.343] [INFO] [BOT:QQ号] - recv from: [Group: 456(11292648), Member: 嗯哼(784456)] 654212
[2021-01-27T09:05:27.257] [TRACE] [BOT:QQ号] - send:Heartbeat.Alive seq:24
[2021-01-27T09:05:27.303] [TRACE] [BOT:QQ号] - recv:Heartbeat.Alive seq:24
[2021-01-27T09:05:44.068] [TRACE] [BOT:QQ号] - recv:OnlinePush.ReqPush seq:-1619003569
[2021-01-27T09:05:44.077] [TRACE] [BOT:QQ号] - send:OnlinePush.RespPush seq:25

**Comment by takayama-lily** [comment] 2021-01-27 07:12
新建了一个bug反馈群：236172566，加一下吗

**Comment by MooMXiZ1** [comment] 2021-01-27 07:15
OK

**Comment by takayama-lily** [comment] 2021-01-27 12:59
Duplicate of #123

**Closed by takayama-lily** 2021-01-27 12:59 UTC
